### ISSUE TITLE
A typo in artifactId

### ISSUE THREAD

**Issue by Twinsen81** [kirich1409/Android-Notification-DSL#4]
Hey Kirill! Thanks for this neat cool library! 
In your latest commit you made a typo in the artifact ID:
`ext.artifactId = 'android-notidification-dsl-core'`
noti**DI**fication instead of **notification**
So the proper gradle.script to include the library is now:
`implementation 'com.github.kirich1409:android-notiDIfication-dsl-core:0.2.0'`

**Comment by kirich1409** [comment]
Will be fixes in 0.2.1
